<?php

return [
    [
        'name' => 'Admin',
        'type' => 1,
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364906,
        'updated_at' => 1736364906,
    ],
    [
        'name' => 'CategoryCreatePermission',
        'type' => 2,
        'description' => 'Permission for CategoryCreatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'CategoryDeletePermission',
        'type' => 2,
        'description' => 'Permission for CategoryDeletePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'CategoryIndexPermission',
        'type' => 2,
        'description' => 'Permission for CategoryIndexPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'CategoryUpdatePermission',
        'type' => 2,
        'description' => 'Permission for CategoryUpdatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'CategoryViewPermission',
        'type' => 2,
        'description' => 'Permission for CategoryViewPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'Client',
        'type' => 1,
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'Employee',
        'type' => 1,
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'Incharge',
        'type' => 1,
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'InvoiceFinishPermission',
        'type' => 2,
        'description' => 'Permission for InvoiceFinishPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'InvoiceIndexPermission',
        'type' => 2,
        'description' => 'Permission for InvoiceIndexPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'InvoiceViewPermission',
        'type' => 2,
        'description' => 'Permission for InvoiceViewPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'ItemAssociatePermission',
        'type' => 2,
        'description' => 'Permission for ItemAssociatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'ItemCreatePermission',
        'type' => 2,
        'description' => 'Permission for ItemCreatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'ItemIndexPermission',
        'type' => 2,
        'description' => 'Permission for ItemIndexPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'ItemRestockPermission',
        'type' => 2,
        'description' => 'Permission for ItemRestockPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'ItemUpdatePermission',
        'type' => 2,
        'description' => 'Permission for ItemUpdatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'ItemViewPermission',
        'type' => 2,
        'description' => 'Permission for ItemViewPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'Manager',
        'type' => 1,
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'SiteActionsPermission',
        'type' => 2,
        'description' => 'Permission for SiteActionsPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'SiteIndexPermission',
        'type' => 2,
        'description' => 'Permission for SiteIndexPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'SiteLoginPermission',
        'type' => 2,
        'description' => 'Permission for SiteLoginPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'SiteLogoutPermission',
        'type' => 2,
        'description' => 'Permission for SiteLogoutPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'StationCreatePermission',
        'type' => 2,
        'description' => 'Permission for StationCreatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'StationDeletePermission',
        'type' => 2,
        'description' => 'Permission for StationDeletePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'StationIndexPermission',
        'type' => 2,
        'description' => 'Permission for StationIndexPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'StationItemAssociatePermission',
        'type' => 2,
        'description' => 'Permission for StationItemAssociatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'StationItemDeleteAssociationPermission',
        'type' => 2,
        'description' => 'Permission for StationItemDeleteAssociationPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'StationItemUpdateAssociationPermission',
        'type' => 2,
        'description' => 'Permission for StationItemUpdateAssociationPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'StationUpdatePermission',
        'type' => 2,
        'description' => 'Permission for StationUpdatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'StationViewPermission',
        'type' => 2,
        'description' => 'Permission for StationViewPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'SubcategoryCreatePermission',
        'type' => 2,
        'description' => 'Permission for SubcategoryCreatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'SubcategoryDeletePermission',
        'type' => 2,
        'description' => 'Permission for SubcategoryDeletePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'SubcategoryUpdatePermission',
        'type' => 2,
        'description' => 'Permission for SubcategoryUpdatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'UserChangerolePermission',
        'type' => 2,
        'description' => 'Permission for UserChangerolePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'UserCreatePermission',
        'type' => 2,
        'description' => 'Permission for UserCreatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'UserDeletePermission',
        'type' => 2,
        'description' => 'Permission for UserDeletePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'UserIndexPermission',
        'type' => 2,
        'description' => 'Permission for UserIndexPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'UserResetPasswordPermission',
        'type' => 2,
        'description' => 'Permission for UserResetPasswordPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'UserUpdatePermission',
        'type' => 2,
        'description' => 'Permission for UserUpdatePermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
    [
        'name' => 'UserViewPermission',
        'type' => 2,
        'description' => 'Permission for UserViewPermission',
        'rule_name' => null,
        'data' => null,
        'created_at' => 1736364907,
        'updated_at' => 1736364907,
    ],
];
