<?php

return [

  [
    'id' => 1,
    'username' => 'admin',
    'auth_key' => 'adminAuthKey',
    'password_hash' => '$2y$10$aWKuiO3Eqm9iYWqOTZT8.eomK7VLcx/evTLXK1R89MZ9/xJ.1P1O.',
    'password_reset_token' => NULL,
    'email' => 'admin@example.com',
    'verification_token' => NULL,
    'status' => 10,
    'created_at' => 0,
    'updated_at' => 0,
  ],

  [
    'id' => 2,
    'username' => 'manager',
    'auth_key' => 'managerAuthKey',
    'password_hash' => '$2y$10$aWKuiO3Eqm9iYWqOTZT8.eomK7VLcx/evTLXK1R89MZ9/xJ.1P1O.',
    'password_reset_token' => NULL,
    'email' => 'manager@example.com',
    'verification_token' => NULL,
    'status' => 10,
    'created_at' => 0,
    'updated_at' => 0,
  ],

  [
    'id' => 3,
    'username' => 'incharge',
    'auth_key' => 'inchargeAuthKey',
    'password_hash' => '$2y$10$aWKuiO3Eqm9iYWqOTZT8.eomK7VLcx/evTLXK1R89MZ9/xJ.1P1O.',
    'password_reset_token' => NULL,
    'email' => 'incharge@example.com',
    'verification_token' => NULL,
    'status' => 10,
    'created_at' => 0,
    'updated_at' => 0,
  ],

  [
    'id' => 4,
    'username' => 'employee',
    'auth_key' => 'employeeAuthKey',
    'password_hash' => '$2y$10$aWKuiO3Eqm9iYWqOTZT8.eomK7VLcx/evTLXK1R89MZ9/xJ.1P1O.',
    'password_reset_token' => NULL,
    'email' => 'employee@example.com',
    'verification_token' => NULL,
    'status' => 10,
    'created_at' => 0,
    'updated_at' => 0,
  ],

  [
    'id' => 5,
    'username' => 'client',
    'auth_key' => 'clientAuthKey',
    'password_hash' => '$2y$10$aWKuiO3Eqm9iYWqOTZT8.eomK7VLcx/evTLXK1R89MZ9/xJ.1P1O.',
    'password_reset_token' => NULL,
    'email' => 'client@example.com',
    'verification_token' => NULL,
    'status' => 10,
    'created_at' => 0,
    'updated_at' => 1731168731,
  ],

  [
    'id' => 6,
    'username' => 'cliente',
    'auth_key' => 'clienteAuthKey',
    'password_hash' => '$2y$10$aWKuiO3Eqm9iYWqOTZT8.eomK7VLcx/evTLXK1R89MZ9/xJ.1P1O.',
    'password_reset_token' => NULL,
    'email' => 'cliente@example.com',
    'verification_token' => NULL,
    'status' => 10,
    'created_at' => 0,
    'updated_at' => 0,
  ],

  [
    'id' => 7,
    'username' => 'teste',
    'auth_key' => '_YAsSf7caKtgmCBLPYNDGcgkoVqPl7Id',
    'password_hash' => '$2y$10$aWKuiO3Eqm9iYWqOTZT8.eomK7VLcx/evTLXK1R89MZ9/xJ.1P1O.',
    'password_reset_token' => NULL,
    'email' => 'client@ct.com',
    'verification_token' => 'ydq-EgDiwmFDEGvX19hFstC94S1uUfUa_1734735189',
    'status' => 10,
    'created_at' => 1734735189,
    'updated_at' => 1734735189,
  ],
];
